version: '3.8'

services:
  lingo:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/app:cached
    command: sleep infinity
    networks:
      - app-network
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://lingo:lingo123@postgres:5432/lingo_dev

  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: lingo
      POSTGRES_PASSWORD: lingo123
      POSTGRES_DB: lingo_dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
