version: '3.8'

services:
  lingo:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/app:cached
    command: sleep infinity
    networks:
      - app-network
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=${DATABASE_URL}

  postgres:
    image: postgres:16
    restart: unless-stopped
    env_file:  
     - ../.env  
    environment:  
      POSTGRES_HOST_AUTH_METHOD: trust  
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
